# Site settings
title: News
email: contact@wevidyanow.com
baseurl: "/news"
url: "https://wevidyanow.com"

# Build settings
markdown: kramdown
permalink: pretty

# Destination
destination: /var/www/news.wevidyanow.com
